# .github/workflows/generate_and_commit_svg.yml
name: Generate and Commit SVG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install svgwrite PyGithub

    - name: Run script to generate SVG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: python generate_svg.py

    - name: Commit and push SVG
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull --rebase
        git add github_username.svg
        git commit -m "Add SVG with GitHub username and stats" || echo "No changes to commit"
        git push
