# .github/workflows/generate_and_commit_svg.yml
name: Generate and Commit SVG Stats

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install svgwrite PyGithub

    - name: Run script to generate SVG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python generate_svg.py

    - name: Commit and push SVG
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        # Make sure local main exactly matches remote
        git fetch origin main
        git reset --hard origin/main
        # (now your working tree is clean)
        git add github_stats.svg
        git commit -m "Update animated stats SVG" || echo "No changes to commit"
        git push

