name: Generate Animated Portfolio

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # 0) Install dependencies
      - name: Install dependencies
        run: |
          pip install svgwrite PyGithub lxml

      # 1) Generate your own snake (or use Platane/snk)
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg

      # 2) (Optional) Generate stats via API + custom script
      - name: Fetch stats & build portfolio SVG
        run: |
          pip install svgwrite PyGithub
          python scripts/build_portfolio.py \
            --contrib dist/snake.svg \
            --output dist/portfolio.svg

      # 3) Deploy to output branch yourself
      - name: Commit and push output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          cp -r dist/* .
          git add .
          git commit -m "Update portfolio at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push -u origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
