name: Build Animated Portfolio

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # 1) Check out your code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Prepare a clean dist/ directory
      - name: Prepare dist directory
        run: |
          # If dist exists as a file, remove it
          if [ -f dist ]; then rm dist; fi
          # Remove old directory (if any) and recreate
          rm -rf dist
          mkdir dist

      # 3) Generate the snake.svg into dist/
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg

      # 4) Install deps & build your portfolio SVG
      - name: Build portfolio SVG
        run: |
          pip install svgwrite PyGithub
          python scripts/build_portfolio.py \
            --contrib dist/snake.svg \
            --output dist/portfolio.svg

      # 5) Commit & push the dist/ files back to an output branch
      - name: Deploy to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          cp -r dist/* .
          git add .
          git commit -m "Portfolio update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push -u origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
